#!/bin/sh

# misc
alias \
    c='clear' \
    ls='eza' \
    cat='bat' \
    rtv='python3 -m rtv' \
    tt='tt -notheme -showwpm -n 20 -oneshot -noreport' \
    v='env TERM=wezterm nvim' \
    b='brew' \
    lg='lazygit' \
    nb='newsboat' \
    cc='changecolors'

# ssh
alias \
    s='ssh'

# youtube-dl
alias \
    yt='yt-dlp --no-abort-on-error --embed-metadata -i' \
    yta="yt-dlp -x -f bestaudio/best"

# tmux
alias \
    t="tmux" \
    ta="tmux attach" \
    ts="tmux-sessionizer"

# docker \
alias \
    d='sudo docker' \
    dc='d compose' \
    dcc='d container' \
    dp='d ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Networks}}\t{{.State}}\t{{.RunningFor}}"'
