#!/bin/sh

# misc
alias \
	c='clear' \
	cat='bat' \
	cc='changecolors' \
	lg='lazygit' \
	ls='eza' \
	nb='newsboat' \
	tt='tt -notheme -showwpm -n 20 -oneshot -noreport' \
	v='env TERM=wezterm nvim'

# ssh
s() {
	selected=$(awk '/^Host / { print $2 }' ~/.ssh/config | fzf)
	[ -n "$selected" ] && ssh "$selected"
}

# youtube-dl
alias \
	dl='yt-dlp --no-abort-on-error --embed-metadata -i --write-thumbnail' \
	dla="yt-dlp -x -f bestaudio/best"

# tmux
alias \
	t="tmux" \
	ta="tmux attach"

# docker \
alias \
	d='sudo docker' \
	dc='d compose' \
	dC='d container' \
	dp='d ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Networks}}\t{{.State}}\t{{.RunningFor}}"'
