#!/bin/sh

### Environment Variables
export FZF_DEFAULT_COMMAND='rg --files'
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --layout=reverse --height=50% --pointer='>' --color 16 --color='fg:gray,bg+:black,hl:cyan,hl+:cyan,info:blue,prompt:white,pointer:magenta'"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --null 2> /dev/null | xargs -0 dirname | sort | uniq"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND 2> /dev/null"
export FZF_COMPLETION_TRIGGER='@'

export BAT_THEME="ansi"
export NODE_COMPILE_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/node-compile-cache"
export OS_APPEARANCE_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/os_theme"
export NOTES_DIR="$(
	[ "$(uname -s)" = "Darwin" ] &&
		echo "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Notes" ||
		echo "$HOME/Documents/notes"
)"

command -v /opt/homebrew/bin/brew >/dev/null && eval "$(/opt/homebrew/bin/brew shellenv)"
command -v fnm >/dev/null && eval "$(fnm env --use-on-cd)"
command -v fzf >/dev/null && eval "$(fzf --zsh)"

### Aliases
alias \
	c='clear' \
	cat='bat' \
	e='$EDITOR' \
	lg='lazygit' \
	ls='eza' \
	n="notarizer" \
	nb='newsboat -u <(cat ~/.config/newsboat/*url*)' \
	note="notarizer" \
	notes="notarizer" \
	tree='eza --tree --icons --group-directories-first --git-ignore'

# ssh
s() {
	selected=$(awk '/^Host / { print $2 }' ~/.ssh/config | grep -v '\*' | fzf)
	[ -n "$selected" ] && ssh "$selected"
}

# git
alias \
	pr='gh pr view --web' \
	repo='gh repo view --web'

g() {
	if [ "$#" -ne 0 ]; then
		git "$@"
	else
		git status
	fi
}

# tmux
alias \
	ta="tmux attach"

t() {
	if [ "$#" -ne 0 ]; then
		tmux "$@"
	else
		tmux-sessionizer
	fi
}

# youtube-dl
alias \
	dl='yt-dlp --no-abort-on-error --ignore-errors --embed-metadata --write-thumbnail' \
	dla="dl --extract-audio --format bestaudio/best"

# docker \
alias \
	d='sudo docker' \
	dc='sudo docker compose' \
	dp='sudo docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Networks}}\t{{.State}}\t{{.RunningFor}}"'

# ai junk
alias \
    cursor='cursor-agent'

ai() {
	cat <<-EOF | fzf | sh
		claude
		cursor-agent
	EOF
}

# typo guards
alias \
	celar='clear' \
	claer='clear' \
	eixt='exit'
