#!/bin/sh

uname -r | grep 'Microsoft' >/dev/null 2>&1 || return

export PATH="/mnt/c/Windows/system32/:$PATH"
export BROWSER=wsl-open

alias \
	shutdown="/mnt/c/Windows/system32/shutdown.exe /s /f /t 0 " \
	reboot="powershell.exe Restart-Computer" \
	open="/usr/local/bin/wsl-open"
