#!/bin/sh

command -v wsl.exe >/dev/null 2>&1 || return

alias \
    clip='/mnt/c/Windows/system32/clip.exe' \
    cmd='/mnt/c/Windows/system32/cmd.exe' \
    open='/mnt/c/Windows/explorer.exe' \
    shutdown="/mnt/c/Windows/system32/shutdown.exe /s /t 0" \
    wsl="/mnt/c/Windows/wsl.exe"
