- name: create .claude directory
  file:
    path: "~/.claude"
    state: directory

- name: symlink claude settings
  file:
    src: "{{ dotfiles_dir }}/config/claude/settings.json"
    path: "~/.claude/settings.json"
    state: link
  tags: ["claude-settings"]

- name: symlink claude CLAUDE.md
  file:
    src: "{{ dotfiles_dir }}/config/claude/CLAUDE.md"
    path: "~/.claude/CLAUDE.md"
    state: link

- name: symlink claude keybindings
  file:
    src: "{{ dotfiles_dir }}/config/claude/keybindings.json"
    path: "~/.claude/keybindings.json"
    state: link

- block:
    - name: create .claude/skills directory
      file:
        path: "~/.claude/skills"
        state: directory

    - name: find all skills in dotfiles
      find:
        paths: "{{ dotfiles_dir }}/config/claude/skills"
        file_type: directory
        recurse: no
      register: find

    - name: symlink skills
      file:
        src: "{{ item.path }}"
        path: "~/.claude/skills/{{ item.path | basename }}"
        state: link
      loop: "{{ find.files }}"
      loop_control:
        label: "{{ item.path }}"
  tags: ["skills"]
