#!/bin/sh
TMUX="/opt/homebrew/bin/tmux"

changeNvimColors() {
    $TMUX list-panes -a -F '#{pane_current_command} #{pane_id}' | while read -r p; do
        target="${p%% *}"
        id="${p##* }"
        if [ "$target" = "nvim" ]; then
            $TMUX send-keys -t "$id" ":call $1()" C-m
        fi
    done
}

changeTmuxColors() {
    $TMUX set-option -g status-style "$1" \; \
       set-option -g window-status-current-style "$2"
}

if [ "$DARKMODE" = 1 ]; then
    changeNvimColors "ChangeColorschemeDark"
    changeTmuxColors "bg=green, fg=black" "bg=green, fg=black"
else
    changeNvimColors "ChangeColorschemeLight"
    changeTmuxColors "bg=black, fg=white" "bg=red, fg=white"
fi
