#!/bin/sh
TMUX="/opt/homebrew/bin/tmux"
OSASCIPT="/usr/bin/osascript"

changeNvimColors() {
    $TMUX list-panes -a -F '#{pane_current_command} #{pane_id}' | while read -r p; do
        target="${p%% *}"
        id="${p##* }"
        if [ "$target" = "nvim" ]; then
            $TMUX send-keys -t "$id" ":set background=$1" C-m
        fi
    done
}

changeSystemColors() {
    $OSASCIPT -l JavaScript -e "Application('System Events').appearancePreferences.darkMode = $1" 1> /dev/null
}

# Auto change when dark mode is changed by system
# 'DARKMODE' set by dark-mode-notify: https://github.com/bouk/dark-mode-notify
if [ "$DARKMODE" = 1 ]; then
    changeNvimColors "dark"
elif [ "$DARKMODE" = 0 ]; then
    changeNvimColors "light"
# Manually change colors
else 
    if [ "$1" = "dark" ]; then
        changeSystemColors "true"
    else
        changeSystemColors "false"
    fi
fi


