#!/bin/bash

set -e

DOTFILES_DIR="$HOME/Developer/dotfiles"
OS="$(uname -s)"

[ "$OS" = "Darwin" ] && PATH="/opt/homebrew/bin:$PATH"

# prompt for sudo password once and pass it to commands that need it
read -rsp 'Password: ' PASSWORD && echo

# # install pip and ansible
! command -v pip3 >/dev/null && curl https://bootstrap.pypa.io/get-pip.py | python3 -
! command -v ansible >/dev/null && (echo "$PASSWORD" | sudo -Skp '' pip3 install --ignore-installed ansible)

# clone dotfiles and run playbook
[ ! -d "$DOTFILES_DIR" ] && git clone "https://github.com/mjsamuel/dotfiles.git" "$DOTFILES_DIR"
ansible-galaxy install -r "$DOTFILES_DIR/ansible/requirements.yml"
ansible-playbook "$DOTFILES_DIR/ansible/playbook.yml" \
    --connection "local" \
    --inventory "localhost," \
    --extra-vars "ansible_become_pass=$PASSWORD"

printf "\n%s\n%s\n" "Setup complete\!" "Open a new terminal window to see changes."
