# Taps
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'romkatv/powerlevel10k'
tap 'teamookla/speedtest'

# Binaries
brew 'bat'
brew 'coreutils' # Those that come with macOS are outdated
brew 'exa'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'golang'
brew 'lazygit'
brew 'mosh'
brew 'neofetch'
brew 'neovim'
brew 'neovim'
brew 'node'
brew 'powerlevel10k'
brew 'python'
brew 'ripgrep'
brew 'silicon'
brew 'speedtest'
brew 'tmux'
brew 'yt-dlp'
brew 'zlib'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

# Apps
cask 'bartender'
cask 'discord'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'iina'
cask 'transmission'
cask 'wezterm'
cask '1password'
cask 'visual-studio-code'
cask 'playdate-simulator'

# Fonts
cask 'font-fira-code-nerd-font'
