#!/bin/sh
DOTFILES_DIR="$HOME/Developer/dotfiles"

echo "Setting up your Mac..."

# Check for Homebrew and install if we don't have it
if test ! "$(which brew)"; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update Homebrew recipes
brew update
# Install all our dependencies with bundle
brew tap homebrew/bundle
brew bundle

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k"

# Remove .zshrc from $HOME (if it exists) and symlinks the .zshrc file from our dotfiles
rm -rf "$HOME/.zshrc"
ln -s "$DOTFILES_DIR/zsh/.zshrc" "$HOME/.zshrc"

# Symlinks
ln -s "$DOTFILES_DIR"/zsh/custom/* "$HOME/.oh-my-zsh/custom/"
ln -s "$DOTFILES_DIR/tmux/" "$HOME/.config/"
ln -s "$DOTFILES_DIR/kitty" "$HOME/.config/"
ln -s "$DOTFILES_DIR/nvim" "$HOME/.config/"
ln -s "$DOTFILES_DIR/wezterm" "$HOME/.config/"
ln -s "$DOTFILES_DIR/other/neofetch" "$HOME/.config/"

# Git setup
ln -s "$DOTFILES_DIR/git/gitconfig" "$HOME/.gitconfig"
git config --global init.templatedir "$DOTFILES_DIR/git/git_template"

# Install tt and symlink theme
sudo curl -L https://github.com/lemnos/tt/releases/download/v0.4.2/tt-osx -o /usr/local/bin/tt && sudo chmod +x /usr/local/bin/tt
sudo curl -o /usr/local/share/man/man1/tt.1.gz -L https://github.com/lemnos/tt/releases/download/v0.4.2/tt.1.gz
mkdir ~/.tt/themes
mkdir -p "$HOME/.tt/themes"
ln -s "$HOME/Developer/dotfiles/other/tt/tt_ayu_theme" "$HOME/.tt/themes/ayu"

neofetch
echo "Install complete"
