#!/bin/sh
DOTFILES_DIR="$HOME/Developer/dotfiles"

echo "Setting up your Mac..."

# Check for Homebrew and install if we don't have it
if test ! "$(which brew)"; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update Homebrew recipes
brew update
# Install all our dependencies with bundle
brew tap homebrew/bundle
brew bundle

# Remove .zprofile from home (if it exists) and symlink new one
rm -rf "$HOME/.zprofile"
ln -s "$DOTFILES_DIR/zsh/.zprofile" "$HOME/"

ln -s "$DOTFILES_DIR/config/" "$HOME/.config/"

# Install tt (typing test)
sudo curl -L 'https://github.com/lemnos/tt/releases/download/v0.4.2/tt-osx' -o '/usr/local/bin/tt' && sudo chmod +x '/usr/local/bin/tt'

# Dark mode notify
git clone 'https://github.com/bouk/dark-mode-notify.git'
ln -s "$DOTFILES_DIR/other/scripts/com.matthewsamuel.dark-mode-notify.plist" "$HOME/Library/LaunchAgents/"
launchctl load -w "$HOME/Library/LaunchAgents/com.matthewsamuel.dark-mode-notify.plist"

neofetch
echo "Install complete"
