#!/bin/sh
DOTFILES_DIR="$HOME/Developer/dotfiles"

echo "Setting up your Mac..."

# Check for Homebrew and install if we don't have it
if test ! "$(which brew)"; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update Homebrew recipes
brew update
# Install all our dependencies with bundle
brew tap homebrew/bundle
brew bundle

# Remove .zshrc from $HOME (if it exists) and symlinks the .zshrc file from our dotfiles
rm -rf "$HOME/.zshrc"
ln -s "$DOTFILES_DIR/zsh/.zshrc" "$HOME/.zshrc"

# Symlinks
ln -s "$DOTFILES_DIR/zsh/custom/" "$HOME/.config/zsh/"
ln -s "$DOTFILES_DIR/tmux/" "$HOME/.config/"
ln -s "$DOTFILES_DIR/kitty" "$HOME/.config/"
ln -s "$DOTFILES_DIR/nvim" "$HOME/.config/"
ln -s "$DOTFILES_DIR/wezterm" "$HOME/.config/"
ln -s "$DOTFILES_DIR/other/neofetch" "$HOME/.config/"

# Git setup
ln -s "$DOTFILES_DIR/git/.gitconfig" "$HOME/.gitconfig"
git config --global init.templatedir "$DOTFILES_DIR/git/git_template"

# Install tt (typing test) and symlink theme
sudo curl -L 'https://github.com/lemnos/tt/releases/download/v0.4.2/tt-osx' -o '/usr/local/bin/tt' && sudo chmod +x '/usr/local/bin/tt'

# Dark mode notify
git clone 'https://github.com/bouk/dark-mode-notify.git'
ln -s "$DOTFILES_DIR/other/scripts/com.matthewsamuel.dark-mode-notify.plist" "$HOME/Library/LaunchAgents/"
launchctl load -w "$HOME/Library/LaunchAgents/com.matthewsamuel.dark-mode-notify.plist"

neofetch
echo "Install complete"
