- name: create XDG directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ XDG_CACHE_HOME }}"
    - "{{ XDG_CACHE_HOME }}/zsh"
    - "{{ XDG_CONFIG_HOME }}"
    - "{{ XDG_DATA_HOME }}"

- name: symlink .zshenv
  file:
    src: "{{ dotfiles_dir }}/config/zsh/.zshenv"
    path: "~/.zshenv"
    state: link

- block:
    - name: find all files in config folder
      find:
        paths: "{{ dotfiles_dir }}/config"
        file_type: "any"
        recurse: no
      register: find

    - name: symlink .config
      file:
        src: "{{ item.path }}"
        path: "{{ XDG_CONFIG_HOME }}/{{ item.path | basename }}"
        state: link
      loop: "{{ find.files }}"
      loop_control:
        label: "{{ item.path }}"

- name: install zsh plugins
  git:
    repo: "{{ item.url }}"
    dest: "{{ zsh_plugins_dir }}/{{ item.name }}"
    clone: true
  become: true
  loop: "{{ zsh_plugins }}"
  loop_control:
    label: "{{ item.name }}"

- block:
    - name: ensure {{fzf_dir}} exists
      file:
        path: "{{ fzf_dir }}"
        state: directory
      become: true

    - name: download fzf keybindings
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh
        dest: "{{ fzf_dir }}/key-bindings.zsh"
      become: true

- name: set zsh as deafult shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_location[ansible_os_family] }}"
  become: true

- name: apply wezterm terminfo
  shell: |
    tempfile=$(mktemp) \
      && curl -o "$tempfile" https://raw.githubusercontent.com/wez/wezterm/master/termwiz/data/wezterm.terminfo \
      && tic -x -o ~/.terminfo "$tempfile" \
      && rm "$tempfile"
