- name: create XDG directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.XDG_CACHE_HOME }}"
    - "{{ ansible_env.XDG_DATA_HOME }}"

- name: symlink .config
  file:
    src: "{{ dotfiles_dir }}/config"
    path: "~/.config"
    state: link

- name: symlink .zprofile
  file:
    src: "{{ dotfiles_dir }}/config/zsh/.zprofile"
    path: "~/.zprofile"
    state: link

- name: set zsh as deafult shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_location[ansible_os_family] }}"
  become: true

- name: apply wezterm terminfo
  shell: |
    tempfile=$(mktemp) \
      && curl -o "$tempfile" https://raw.githubusercontent.com/wez/wezterm/master/termwiz/data/wezterm.terminfo \
      && tic -x -o ~/.terminfo "$tempfile" \
      && rm "$tempfile"
