- name: create XDG directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ XDG_CACHE_HOME }}"
    - "{{ XDG_CONFIG_HOME }}"
    - "{{ XDG_DATA_HOME }}"

- name: find all files in config folder
  find:
    paths: "{{ dotfiles_dir }}/config"
    file_type: "any"
    recurse: no
  register: find

- name: symlink .config
  file:
    src: "{{ item.path }}"
    path: "{{ XDG_CONFIG_HOME }}/{{ item.path | basename }}"
    state: link
  loop: "{{ find.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: symlink .zprofile
  file:
    src: "{{ dotfiles_dir }}/config/zsh/.zprofile"
    path: "~/.zprofile"
    state: link

- name: install zsh plugins
  git:
    repo: "{{ item.url }}"
    dest: "{{ zsh_plugins_dir }}/{{ item.name }}"
    force: yes
    clone: true
  loop: "{{ zsh_plugins }}"
  when: ansible_os_family != "Darwin"

- name: download fzf keybindings
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh
    dest: /usr/share/doc/fzf/examples/key-bindings.zsh
  become: true
  when: ansible_os_family != "Darwin"

- name: set zsh as deafult shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_location[ansible_os_family] }}"
  become: true

- name: apply wezterm terminfo
  shell: |
    tempfile=$(mktemp) \
      && curl -o "$tempfile" https://raw.githubusercontent.com/wez/wezterm/master/termwiz/data/wezterm.terminfo \
      && tic -x -o ~/.terminfo "$tempfile" \
      && rm "$tempfile"
