- name: install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: "/opt/homebrew/bin"
  become: true
  become_user: root

- name: add custom homebrew repos
  community.general.homebrew_tap:
    name: [homebrew/cask-fonts, romkatv/powerlevel10k, teamookla/speedtest]

- name: install packages
  community.general.homebrew:
    name:
      - bat # prettier 'cat'
      - coreutils # those that come with macOS are outdated
      - exa # prettier 'ls'
      - fd # faster 'find'
      - ffmpeg
      - fnm # node version manager
      - fzf # fuzzy finder
      - git
      - git-delta # prettier diffs
      - lazygit # 'git' gui
      - mas
      - mosh
      - neofetch
      - newsboat # rss reader
      - powerlevel10k
      - python
      - ripgrep # faster 'grep'
      - silicon # code screenshot tool
      - speedtest
      - stow
      - tmux
      - yt-dlp
      - zlib
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present
    update_homebrew: no

- name: install gui app
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - 1password
    - alt-tab
    - bartender
    - discord
    - docker
    - firefox
    - font-fira-code-nerd-font
    - google-chrome
    - iina
    - playdate-simulator
    - transmission
    - visual-studio-code
    - wezterm

- name: Install Mac app store apps
  community.general.mas:
    id:
      - 1438243180 # dark reader for safari
      - 1440147259 # adguard for safari
      - 1475387142 # tailscale
      - 1480933944 # vimari
      - 1555925018 # genki arcade
      - 1569813296 # 1password for safari
      - 409201541 # pages
      - 497799835 # xcode
    state: present
