- block:
    - name: install homebrew packages
      include_role:
        name: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - name: install mac apps
      include_role:
        name: geerlingguy.mac.mas
        apply:
          ignore_errors: true
      tags: ["mas"]
  when: ansible_os_family == "Darwin"

- block:
    - name: install apt packages (Debian)
      ansible.builtin.apt:
        name: "{{ apt_installed_packages }}"
        state: present
      become: true
  when: ansible_os_family == "Debian"

- name: install github release binaries
  include_tasks: github_release.yml
  loop: "{{ github_releases }}"
  loop_control:
    loop_var: pkg
    label: "{{ pkg.binary }}"
  when: ansible_os_family != "Darwin"

- name: fnm install latest lts
  shell: fnm install --lts
  register: fnm_install
  changed_when: 'fnm_install.stderr is not search("Version already installed")'

- name: fnm set lts as default
  shell: |
    eval "$(fnm env)"
    fnm default lts/latest
  when: fnm_install is changed
