#!/bin/sh
STATE_FILE="$XDG_CACHE_HOME/os_theme"
OS="$(uname -s)"

changeThemeMac() {
	[ "$1" = "dark" ] && darkMode="true" || darkMode="false"
	/usr/bin/osascript -l JavaScript -e \
		"Application('System Events').appearancePreferences.darkMode = $darkMode" \
		>/dev/null 2>&1
}

changeNvimColors() {
	tmux list-panes -a -F '#{pane_current_command} #{pane_id}' | while read -r p; do
		target="${p%% *}"
		id="${p##* }"
		if [ "$target" = "nvim" ]; then
			tmux send-keys -t "$id" Escape ":set background=$1" C-m
		fi
	done
}

{ [ "$1" = "dark" ] || [ "$1" = "light" ]; } && theme="$1"
if [ "$OS" = "Darwin" ]; then
	switcher="changeThemeMac"
	if [ -z "$theme" ]; then
		/usr/bin/defaults read -g AppleInterfaceStyle >/dev/null 2>&1 &&
			theme="light" ||
			theme="dark"
	fi
else
	grep "dark" "$STATE_FILE" >/dev/null && theme="light" || theme="dark"
fi

$switcher "$theme"
changeNvimColors "$theme"

echo "$theme" >"$STATE_FILE"
