#!/bin/sh
STATE_FILE="$XDG_CACHE_HOME/os_theme"

changeThemeMac() {
	[ "$1" = "dark" ] && darkMode="true" || darkMode="false"
	/usr/bin/osascript -l JavaScript -e \
		"Application('System Events').appearancePreferences.darkMode = $darkMode" \
		>/dev/null 2>&1
}

changeThemeWsl() {
	[ "$1" = "dark" ] && mode="0" || mode="1"
	powershell.exe 'Set-ItemProperty `
        -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize `
        -Name AppsUseLightTheme `
        -Value' "$mode"
}

changeNvimColors() {
	tmux list-panes -a -F '#{pane_current_command} #{pane_id}' | while read -r p; do
		target="${p%% *}"
		id="${p##* }"
		if [ "$target" = "nvim" ]; then
			tmux send-keys -t "$id" Escape ":set background=$1" C-m
		fi
	done
}

{ [ "$1" = "dark" ] || [ "$1" = "light" ]; } && theme="$1"

OS="$(uname -s)"
if [ "$OS" = "Darwin" ]; then
	switcher="changeThemeMac"
	if [ -z "$theme" ]; then
		/usr/bin/defaults read -g AppleInterfaceStyle >/dev/null 2>&1 &&
			theme="light" ||
			theme="dark"
	fi
elif command -v wsl.exe >/dev/null 2>&1 || return; then
	switcher="changeThemeWsl"
	powershell.exe 'Get-ItemProperty `
    -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize `
    -Name AppsUseLightTheme' | grep 1 >/dev/null 2>&1 &&
		theme="dark" ||
		theme="light"
else
	grep "dark" "$STATE_FILE" >/dev/null && theme="light" || theme="dark"
fi

[ ! -z "$switcher" ] && $switcher "$theme"
changeNvimColors "$theme"

echo "$theme" >"$STATE_FILE"
