#!/bin/sh
OS_APPEARANCE_FILE="${OS_APPEARANCE_FILE:-$XDG_CACHE_HOME/os_theme}"

changeThemeMac() {
	[ "$1" = "dark" ] && darkMode="true" || darkMode="false"
	/usr/bin/osascript -l JavaScript -e \
		"Application('System Events').appearancePreferences.darkMode = $darkMode" \
		>/dev/null 2>&1
}

changeThemeWsl() {
	[ "$1" = "dark" ] && mode="0" || mode="1"
	powershell.exe 'Set-ItemProperty `
        -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize `
        -Name AppsUseLightTheme `
        -Value' "$mode"
}

changeNvimColors() {
	tmux_running=$(pgrep tmux)
    [ -z "$tmux_running" ] && return
	tmux list-panes -a -F '#{pane_current_command} #{pane_id}' | while read -r p; do
		target="${p%% *}"
		id="${p##* }"
		if [ "$target" = "nvim" ]; then
			tmux send-keys -t "$id" Escape ":set background=$1" C-m
		fi
	done
}

OS="$(uname -s)"
if [ "$OS" = "Darwin" ]; then
	switcher="changeThemeMac"
	/usr/bin/defaults read -g AppleInterfaceStyle >/dev/null 2>&1 &&
		theme="light" ||
		theme="dark"
elif command -v wsl.exe >/dev/null 2>&1 || return; then
	switcher="changeThemeWsl"
	powershell.exe 'Get-ItemProperty `
    -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize `
    -Name AppsUseLightTheme' | grep 1 >/dev/null 2>&1 &&
		theme="dark" ||
		theme="light"
else
	grep "dark" "$OS_APPEARANCE_FILE" >/dev/null && theme="light" || theme="dark"
fi

[ -n "$switcher" ] && $switcher "$theme"
changeNvimColors "$theme"

echo "$theme" >"$OS_APPEARANCE_FILE"
