#!/bin/sh
WORKSPACES_FILE="$HOME/.config/workspaces"

selected="$(find $(xargs <"$WORKSPACES_FILE") -mindepth 1 -maxdepth 1 -type d | fzf $FZF_DEFAULT_OPTS)"
[ -z "$selected" ] && exit 0
selected_name=$(basename "$selected" | tr . _)

tmux_running=$(pgrep tmux)
session_exists=$(tmux list-sessions | grep "$selected_name")
if [ -z "$tmux_running" ] || [ -z "$session_exists" ]; then
	tmux new-session -ds "$selected_name" -c "$selected"
fi

in_tmux="$TMUX"
if [ -z "$in_tmux" ]; then
	tmux attach -t "$selected_name"
else
	tmux switch-client -t "$selected_name"
fi
