#!/bin/sh

WORKSPACES_FILE="$HOME/.config/workspaces"
session_exists() {
    tmux list-sessions | grep "$selected_name"
}

selected="$(find $(xargs <"$WORKSPACES_FILE") -mindepth 1 -maxdepth 1 -type d | fzf $FZF_DEFAULT_OPTS)"
[ -z "$selected" ] && exit 0
selected_name=$(basename "$selected" | tr . _)

in_tmux="$TMUX"
tmux_running=$(pgrep tmux)
if { [ -z "$tmux_running" ] && [ -z "$in_tmux" ]; } ||
    { [ -z "$in_tmux" ] && [ -z "$(session_exists)" ]; }; then
    tmux new-session -s "$selected_name" -c "$selected"
else
    [ -z "$(session_exists)" ] && tmux new-session -ds "$selected_name" -c "$selected"
    tmux switch-client -t "$selected_name"
fi
