- name: Setup local workstation
  hosts: localhost
  environment:
    XDG_CACHE_HOME: "{{ XDG_CACHE_HOME }}"
    XDG_CONFIG_HOME: "{{ XDG_CONFIG_HOME }}"
    XDG_DATA_HOME: "{{ XDG_DATA_HOME }}"
  vars:
    dotfiles_dir: "{{ ansible_env.PWD | dirname }}"
    XDG_CACHE_HOME: "{{ ansible_env.HOME }}/.cache/"
    XDG_CONFIG_HOME: "{{ ansible_env.HOME }}/.config/"
    XDG_DATA_HOME: "{{ ansible_env.HOME }}/.local/share"

  roles:
    - role: packages
      tags: ["packages"]
    - role: shell
      tags: ["shell"]
    - role: ssh
      tags: ["ssh"]
    - role: neovim
      tags: ["neovim", "nvim"]
    - role: tmux
      tags: ["tmux"]
    - role: tt
      tags: ["tt"]
