- name: Setup local workstation
  hosts: localhost
  environment:
    XDG_CACHE_HOME: "{{ ansible_env.HOME }}/.cache/"
    XDG_CONFIG_HOME: "{{ ansible_env.HOME }}/.config/"
    XDG_DATA_HOME: "{{ ansible_env.HOME }}/.local/share"
  vars:
    dotfiles_dir: "{{ ansible_env.PWD }}/.."

  roles:
    - role: packages
      tags: ["packages"]
    - role: zsh
      tags: ["zsh"]
    - role: ssh
      tags: ["ssh"]
    - role: neovim
      tags: ["neovim", "nvim"]
    - role: tmux
      tags: ["tmux"]
