alias c='clear'
alias ls='exa'
alias cat='bat'
alias s='ssh'
alias sshhosts="grep -w -i -E 'Host|HostName' ~/.ssh/config | sed 's/Host //' | sed 's/HostName //'"
alias rtv='python3 -m rtv'
alias tt='tt -theme ayu -showwpm'
alias v='nvim'
alias b='brew'
alias yt='yt-dlp --no-abort-on-error --embed-metadata -i'
alias yta="yt -x -f bestaudio/best"
