onboarding = false

[terminal]
new_cwd = "follow"

[theme]
auto_switch = true
dark_name   = "rose-pine"
light_name  = "rose-pine-dawn"

[ui]
mouse_capture                    = true
pane_borders                     = true
pane_outer_borders               = false
pane_gaps                        = false
prompt_new_tab_name              = false
prompt_new_workspace_name        = true
accent                           = "blue"
tab_bar_position                 = "top"
agent_panel_sort = "spaces"
right_click_passthrough_modifier = "alt"
status_indicators = "dots"

[ui.sidebar.agents.rows_by_agent]
pi = [
    ["state_icon", "workspace", "tab"],
    ["$summary"],
]

[ui.toast]
herdr.position    = "top-right"
clipboard.enabled = false
delivery          = "herdr"

[keys]
prefix = "ctrl+b"

# Workspaces
navigate_workspace_down = "j"
navigate_workspace_up   = "k"
new_workspace           = "prefix+shift+c"
next_workspace          = "alt+j"
previous_workspace      = "alt+k"

# Agents
next_agent     = "alt+shift+j"
previous_agent = "alt+shift+k"

# Tabs
move_tab_next     = "alt+>"
move_tab_previous = "alt+<"

# Panes
last_pane        = "alt+l"

# Worktrees
new_worktree  = "alt+shift+w"
open_worktree = "alt+w"

[[keys.command]]
key         = "prefix+o"
type        = "plugin_action"
command     = "mjsamuel.even-panes.even-panes"
description = "evenly resize panes"

[[keys.command]]
key         = "prefix+s"
type        = "popup"
command     = "herdr-sessionizer"
description = "herdr-sessionizer"
width       = "80%"
height      = "80%"

[[keys.command]]
key         = "prefix+n"
type        = "popup"
command     = "notarizer"
description = "notarizer"
width       = "80%"
height      = "80%"

[[keys.command]]
key         = "prefix+space"
type        = "popup"
command     = "~/Developer/herdr-pallete/dist/herdr-pallete"
description = "palette"
width       = "80%"
height      = "80%"

[worktrees]
directory = "~/.local/share/worktrees"

[experimental]
kitty_graphics = true
