onboarding = false

[terminal]
new_cwd = "follow"

[theme]
auto_switch = true
dark_name   = "rose-pine"
light_name  = "rose-pine-dawn"

[ui]
mouse_capture                    = true
pane_borders                     = true
pane_outer_borders               = false
pane_gaps                        = false
prompt_new_tab_name              = true
prompt_new_workspace_name        = true
accent                           = "blue"
tab_bar_position                 = "top"
agent_panel_sort                 = "spaces"
right_click_passthrough_modifier = "alt"
status_indicators                = "symbols"

[ui.toast]
herdr.position    = "top-right"
clipboard.enabled = false

[keys]
prefix = "ctrl+b"

# Workspaces
navigate_workspace_down = "j"
navigate_workspace_up   = "k"
new_workspace           = "prefix+shift+c"

# Agents
next_agent     = "alt+j"
previous_agent = "alt+k"

# Tabs
move_tab_previous = "alt+<"
move_tab_next     = "alt+>"

# Panes
last_pane        = "alt+l"

# Worktrees
new_worktree  = "alt+shift+w"
open_worktree = "alt+w"

[[keys.command]]
key         = "alt+shift+s"
type        = "popup"
command     = "herdr-sessionizer"
description = "herdr-sessionizer"
width       = "80%"
height      = "80%"

[[keys.command]]
key         = "alt+shift+n"
type        = "popup"
command     = "notarizer"
description = "notarizer"
width       = "80%"
height      = "80%"

[worktrees]
directory = "~/.local/share/worktrees"
