### messages
set -g message-style "bg=terminal, fg=yellow" # dialog when ':' is pressed
set -g mode-style "bg=yellow,fg=black" # line number indicator when in copy mode

### panes
set -g pane-border-style "bg=terminal, fg=white dim" # default styling for inactive panes
set -g pane-active-border-style "fg=white bright"

### status
set -g status-position "bottom"
set -g status-interval 1
set -g status-justify "centre"
set -g status-style "bg=terminal, fg=white dim" # default styling for status bar items

# status left
%hidden STATUS_LEFT="#{session_name}#{?#{E:SSH_CONNECTION},@#h,}"
%hidden STATUS_LEFT_LENGTH="24"
set -g status-left "$STATUS_LEFT"
set -g status-left-length "$STATUS_LEFT_LENGTH"

# status right
set -g status-right "$STATUS_LEFT"
set -g status-right-length "$STATUS_LEFT_LENGTH"
set -g status-right-style "hidden"

### popup window
set -g popup-style "bg=terminal, fg=white"
set -g popup-border-style "bg=terminal, fg=white"
set -g popup-border-lines "rounded"
set -g menu-border-lines "rounded"

### tabs
%hidden WINDOW_INDEX="#{?window_last_flag,l,#{window_index}}" # show 'l' instead of the window index if it's the last window in the session
%hidden APP_ICON="#($XDG_CONFIG_HOME/tmux/bin/app-icon.sh '#{window_name}' '#{pane_current_command}' '#{window_active}')"
%hidden PANE_ICON="#{?window_zoomed_flag,,$APP_ICON}"
%hidden TAB_NAME="#{?#{<:#{client_width},#{client_height}},#{window_name},#{=1:window_name}}" # display first letter of window name if srceen height is greater than screen width

%hidden STATUS_FORMAT="$WINDOW_INDEX $PANE_ICON $TAB_NAME"
set -g window-status-format "$STATUS_FORMAT"
set -g window-status-current-format "$STATUS_FORMAT"

set -g window-status-separator '  '
set -g window-status-current-style "nodim"

set -g window-status-bell-style 'curly-underscore'
